/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-10-02 21:47:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.syos.domain.model.Product;
import com.syos.domain.model.Discount;
import com.syos.domain.model.User;

public final class products_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/common/footer.jsp", Long.valueOf(1759437206368L));
    _jspx_dependants.put("/WEB-INF/jsp/common/header.jsp", Long.valueOf(1759437198544L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.syos.domain.model.Discount");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.syos.domain.model.Product");
    _jspx_imports_classes.add("com.syos.domain.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setAttribute("pageTitle", "Products");

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    String userRole = (String) session.getAttribute("userRole");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SYOS - ");
      out.print( request.getAttribute("pageTitle") != null ? request.getAttribute("pageTitle") : "Supermarket Billing System" );
      out.write("</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print( request.getContextPath() );
      out.write("/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\">SYOS</a>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("                    ");
 if (user != null) { 
      out.write("\r\n");
      out.write("                        ");
 if ("ADMIN".equals(userRole) || "STAFF".equals(userRole)) { 
      out.write("\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/dashboard.jsp\">Dashboard</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/products/list.jsp\">Products</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/inventory/stocks.jsp\">Inventory</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/billing/create-bill.jsp\">Billing</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/reports/daily-sales.jsp\">Reports</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/products.jsp\">Products</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/customer/cart.jsp\">Cart</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/customer/orders.jsp\">My Orders</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/products.jsp\">Products</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"navbar-nav\">\r\n");
      out.write("                    ");
 if (user != null) { 
      out.write("\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                                Welcome, ");
      out.print( user.getFirstName() );
      out.write("\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\">Logout</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/login.jsp\">Login</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/register.jsp\">Register</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
 String error = (String) request.getAttribute("error"); 
      out.write("\r\n");
      out.write("        ");
 if (error != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-danger alert-dismissible fade show mt-3\" role=\"alert\">\r\n");
      out.write("                ");
      out.print( error );
      out.write("\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 String success = (String) request.getAttribute("success"); 
      out.write("\r\n");
      out.write("        ");
 if (success != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-success alert-dismissible fade show mt-3\" role=\"alert\">\r\n");
      out.write("                ");
      out.print( success );
      out.write("\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <div class=\"col-12\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("            <h2>Our Products</h2>\r\n");
      out.write("            <div class=\"d-flex gap-2\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"searchInput\" placeholder=\"Search products...\">\r\n");
      out.write("                <select class=\"form-select\" id=\"categoryFilter\">\r\n");
      out.write("                    <option value=\"\">All Categories</option>\r\n");
      out.write("                    <!-- Categories would be populated dynamically -->\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
 String error = (String) request.getAttribute("error"); 
      out.write("\r\n");
      out.write("        ");
 if (error != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("                ");
      out.print( error );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\" id=\"productsContainer\">\r\n");
      out.write("            ");

                // This would normally come from a servlet, but for now we'll show a placeholder
                List<Product> products = (List<Product>) request.getAttribute("products");
                if (products != null && !products.isEmpty()) {
                    for (Product product : products) {
            
      out.write("\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 mb-4\">\r\n");
      out.write("                    <div class=\"card product-card h-100\">\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        ");
 Discount discount = (Discount) product.getDiscount(); 
      out.write("\r\n");
      out.write("                        ");
 if (discount != null) { 
      out.write("\r\n");
      out.write("                            <div class=\"discount-badge\">\r\n");
      out.write("                                ");
      out.print( discount.getDiscountType() == com.syos.domain.enums.DiscountType.PERCENT ?
                                    discount.getValue() + "% OFF" : "$" + discount.getValue() + " OFF" );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"card-body d-flex flex-column\">\r\n");
      out.write("                            <h5 class=\"card-title\">");
      out.print( product.getName() );
      out.write("</h5>\r\n");
      out.write("                            <p class=\"card-text text-muted small\">Code: ");
      out.print( product.getCode() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mt-auto\">\r\n");
      out.write("                                ");
 if (discount != null) { 
      out.write("\r\n");
      out.write("                                    <div class=\"mb-2\">\r\n");
      out.write("                                        <span class=\"original-price\">$");
      out.print( String.format("%.2f", product.getPrice()) );
      out.write("</span>\r\n");
      out.write("                                        <span class=\"price ms-2\">$");
      out.print( String.format("%.2f", product.getDiscountedPrice()) );
      out.write("</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    <div class=\"price mb-2\">$");
      out.print( String.format("%.2f", product.getPrice()) );
      out.write("</div>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"d-flex gap-2\">\r\n");
      out.write("                                    <input type=\"number\" class=\"form-control form-control-sm\" value=\"1\" min=\"1\"\r\n");
      out.write("                                           id=\"quantity-");
      out.print( product.getCode() );
      out.write("\" style=\"width: 80px;\">\r\n");
      out.write("                                    <button class=\"btn btn-primary btn-sm flex-grow-1 add-to-cart-btn\"\r\n");
      out.write("                                            data-product-code=\"");
      out.print( product.getCode() );
      out.write("\"\r\n");
      out.write("                                            data-product-name=\"");
      out.print( product.getName().replaceAll("\"", """) );
      out.write("\"\r\n");
      out.write("                                            data-price=\"");
      out.print( product.getDiscountedPrice() );
      out.write("\">\r\n");
      out.write("                                        Add to Cart\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");

                    }
                } else {
            
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"text-center py-5\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <i class=\"fas fa-box-open fa-3x text-muted\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-muted\">No products available</h4>\r\n");
      out.write("                        <p class=\"text-muted\">Please check back later or contact support.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            // This would normally be loaded via AJAX or server-side rendering\r\n");
      out.write("            if (document.querySelectorAll('#productsContainer .col-md-6').length === 0) {\r\n");
      out.write("                const sampleProducts = [\r\n");
      out.write("                    { code: 'MILK001', name: 'Fresh Milk 1L', price: 2.50, discountedPrice: 2.50 },\r\n");
      out.write("                    { code: 'BREAD001', name: 'Whole Wheat Bread', price: 3.00, discountedPrice: 2.50 },\r\n");
      out.write("                    { code: 'EGGS001', name: 'Farm Eggs (12)', price: 4.50, discountedPrice: 4.50 },\r\n");
      out.write("                    { code: 'BANANA001', name: 'Bananas (kg)', price: 1.20, discountedPrice: 1.20 },\r\n");
      out.write("                    { code: 'CHEESE001', name: 'Cheddar Cheese 200g', price: 5.50, discountedPrice: 4.95 },\r\n");
      out.write("                    { code: 'TOMATO001', name: 'Tomatoes (kg)', price: 2.80, discountedPrice: 2.80 }\r\n");
      out.write("                ];\r\n");
      out.write("\r\n");
      out.write("                let html = '';\r\n");
      out.write("                sampleProducts.forEach(product => {\r\n");
      out.write("                    html += `\r\n");
      out.write("                        <div class=\"col-md-6 col-lg-4 mb-4\">\r\n");
      out.write("                            <div class=\"card product-card h-100\">\r\n");
      out.write("                                <div class=\"card-body d-flex flex-column\">\r\n");
      out.write("                                    <h5 class=\"card-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                                    <p class=\"card-text text-muted small\">Code: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                                    <div class=\"mt-auto\">\r\n");
      out.write("                                        <div class=\"price mb-2\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.discountedPrice.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                        <div class=\"d-flex gap-2\">\r\n");
      out.write("                                            <input type=\"number\" class=\"form-control form-control-sm\" value=\"1\" min=\"1\"\r\n");
      out.write("                                                   id=\"quantity-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 80px;\">\r\n");
      out.write("                                            <button class=\"btn btn-primary btn-sm flex-grow-1\"\r\n");
      out.write("                                                    onclick=\"addToCart('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.discountedPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", parseInt(document.getElementById('quantity-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("').value))\">\r\n");
      out.write("                                                Add to Cart\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    `;\r\n");
      out.write("                });\r\n");
      out.write("                document.getElementById('productsContainer').innerHTML = html;\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Add to cart functionality\r\n");
      out.write("document.addEventListener('click', function(e) {\r\n");
      out.write("    if (e.target.classList.contains('add-to-cart-btn')) {\r\n");
      out.write("        const button = e.target;\r\n");
      out.write("        const productCode = button.getAttribute('data-product-code');\r\n");
      out.write("        const productName = button.getAttribute('data-product-name');\r\n");
      out.write("        const price = parseFloat(button.getAttribute('data-price'));\r\n");
      out.write("        const quantityInput = document.getElementById('quantity-' + productCode);\r\n");
      out.write("        const quantity = parseInt(quantityInput.value);\r\n");
      out.write("\r\n");
      out.write("        addToCart(productCode, productName, price, quantity);\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// Search functionality\r\n");
      out.write("document.getElementById('searchInput').addEventListener('input', function() {\r\n");
      out.write("    const searchTerm = this.value.toLowerCase();\r\n");
      out.write("    const productCards = document.querySelectorAll('.product-card');\r\n");
      out.write("\r\n");
      out.write("    productCards.forEach(card => {\r\n");
      out.write("        const productName = card.querySelector('.card-title').textContent.toLowerCase();\r\n");
      out.write("        const productCode = card.querySelector('.card-text').textContent.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("        if (productName.includes(searchTerm) || productCode.includes(searchTerm)) {\r\n");
      out.write("            card.style.display = 'block';\r\n");
      out.write("        } else {\r\n");
      out.write("            card.style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    </div> <!-- End container-fluid -->\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"bg-dark text-light mt-5 py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <h5>SYOS</h5>\r\n");
      out.write("                    <p class=\"mb-0\">Supermarket Billing System</p>\r\n");
      out.write("                    <small class=\"text-muted\">Efficient inventory and billing management</small>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-md-end\">\r\n");
      out.write("                    <p class=\"mb-0\">&copy; 2024 SYOS System. All rights reserved.</p>\r\n");
      out.write("                    <small class=\"text-muted\">Version 1.0.0</small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
